/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.fomdeskapp.toolsapp.Frames;

/**
 *
 * @author emerson.guevara
 */
public class MonedasFrame extends javax.swing.JFrame {

    /** Creates new form CurrencyFormStep1 */
    public MonedasFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cfsAmountlb = new javax.swing.JLabel();
        csfAmountTxt = new javax.swing.JTextField();
        csfConversionCb = new javax.swing.JComboBox<>();
        csfConversionlb = new javax.swing.JLabel();
        cfsNextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cfsAmountlb.setText("Cantidad");

        csfAmountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csfAmountTxtActionPerformed(evt);
            }
        });

        csfConversionCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "USD a Euro", "USD a Libreas Esterlinas", "USD a Yen Japones", "USD a Won", "Euro a USD", "Libras Esterlinas a USD", "Yen Japones a USD", "Won a USD" }));
        csfConversionCb.setSelectedItem("");
        csfConversionCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csfConversionCbActionPerformed(evt);
            }
        });

        csfConversionlb.setText("Conversion");

        cfsNextBtn.setText("Next");
        cfsNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfsNextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cfsAmountlb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csfAmountTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(csfConversionlb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(csfConversionCb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cfsNextBtn)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cfsAmountlb)
                    .addComponent(csfAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csfConversionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csfConversionlb))
                .addGap(63, 63, 63)
                .addComponent(cfsNextBtn)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cfsNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfsNextBtnActionPerformed
        // TODO add your handling code here:
        String[] args = new String[2];
        args[0]= (String) csfConversionCb.getSelectedItem();
        args[1]= (String) csfAmountTxt.getText();
        System.out.println(args[0]);
        System.out.println(args[1]);
        MonedasResultFrame formStep2 = new MonedasResultFrame(args);
        formStep2.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cfsNextBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void csfAmountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csfAmountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csfAmountTxtActionPerformed

    private void csfConversionCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csfConversionCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csfConversionCbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonedasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cfsAmountlb;
    private javax.swing.JButton cfsNextBtn;
    private javax.swing.JTextField csfAmountTxt;
    private javax.swing.JComboBox<String> csfConversionCb;
    private javax.swing.JLabel csfConversionlb;
    // End of variables declaration//GEN-END:variables
    private String name = this.name;
}
